# Generated by Django 4.1.2 on 2022-10-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="uploads/avatar/default.png",
                upload_to="uploads/avatar/%Y/%m/%d/",
                verbose_name="Аватарка",
            ),
        ),
    ]
